spring.application.name=SentinelX Core API
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelx
spring.datasource.username=sentinelx_app
spring.datasource.password=${SENTINELX_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never
